name: Deploy Application Via SSH

on:
  push:
    branches: [ master ]

jobs:
  # // JOB 1
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Compile CSS and Javascript
          run: |
            npm install
            npm run prod

        - name: Configure PHP 8.0
          uses: shivammathur/setup-php@master
          with:
            php-version: 8.2
            extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
        
        - name: Composer install
          run: |
            composer install --no-dev --no-interaction --prefer-dist
        
        
  name: "${{ matrix.server.name }}: Clean up"
  runs-on: ubuntu-latest
  needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks, activate-release, run-after-hooks ]
  strategy:
    matrix:
      server: ${{ fromJson(needs.create-deployment-artifacts.outputs.DEPLOYMENT_MATRIX) }}
  steps:
    - name: Run after hooks
      uses: appleboy/ssh-action@master
      env:
        RELEASES_PATH: ${{ matrix.server.path }}/releases
        ARTIFACTS_PATH: ${{ matrix.server.path }}/artifacts
      with:
        host: ${{ matrix.server.ip }}
        username: ${{ matrix.server.username }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ matrix.server.port }}
        envs: RELEASES_PATH
        script: |
          cd $RELEASES_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
          cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf