name: Deploy Application Via SSH

on:
  push:
    branches: [ master ]

jobs:
  # // JOB 1
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Compile CSS and Javascript
          run: |
            npm install
            npm run prod

        - name: Configure PHP 8.0
          uses: shivammathur/setup-php@master
          with:
            php-version: 8.2
            extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
        
        - name: Composer install
          run: |
            composer install --no-dev --no-interaction --prefer-dist
        # //
        - name: Put all the projet to one file
          env:
            GITHUB_SHA: ${{ github.sha }}
          run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
        
        - name: Store artifact to app-bluid for distribution
          uses: actions/upload-artifact@v3
          with:
            name: app-build
            path: ${{ github.sha }}.tar.gz

        - name: Export deployment matrix
          id: export-deployment-matrix
          run: |
              delimiter="$(openssl rand -hex 8)"
              JSON="$(cat ../deployement-config.json)"
              echo "DEPLOYMENT_MATRIX<<${delimiter}" >> "${GITHUB_OUTPUT}"
              echo "$JSON" >> "${GITHUB_OUTPUT}"
              echo "${delimiter}" >> "${GITHUB_OUTPUT}"